let data=ctkLoadData();
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function save(){ctkSaveData(data);const b=$('saveAll');if(b){b.textContent='Saved ✓';b.classList.add('saved');setTimeout(()=>{b.textContent='Save Changes';b.classList.remove('saved')},1200)}showToast('Saved successfully');}
function showToast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function render(){renderDashboard();renderSettings();renderServices();renderPlatforms();}
function renderDashboard(){$('dashboard').innerHTML=`<div class="stats"><div class="stat"><b>${data.services.length}</b><span>Total services</span></div><div class="stat"><b>${data.services.filter(x=>x.active).length}</b><span>Active services</span></div><div class="stat"><b>${data.platforms.length}</b><span>Platforms</span></div><div class="stat"><b>${data.platforms.filter(x=>x.active).length}</b><span>Active platforms</span></div></div><div class="grid2"><div class="card"><h2>Quick actions</h2><div class="actions"><button class="btn primary" onclick="openService()">+ Add Service</button><button class="btn" onclick="openPlatform()">+ Add Platform</button><button class="btn" onclick="go('settings')">Edit Site Settings</button></div></div><div class="card"><h2>Current website</h2><p style="color:#667085;font-size:13px">Changes in this demo panel are stored in this browser. Supabase connection can be enabled later without changing the admin interface.</p></div></div>`}
function renderSettings(){$('settings').innerHTML=`<div class="card"><h2>Site Settings</h2><div class="grid2"><div><div class="field"><label>Site Name</label><input id="sName" value="${esc(data.settings.siteName)}"></div><div class="field"><label>Tagline</label><textarea id="sTag">${esc(data.settings.tagline)}</textarea></div><div class="field"><label>WhatsApp Display Number</label><input id="sWa" value="${esc(data.settings.whatsapp)}"></div></div><div><div class="field"><label>WhatsApp Number (digits only)</label><input id="sWan" value="${esc(data.settings.whatsappNumber)}"></div><div class="field"><label>Followers Stat</label><input id="sFol" value="${esc(data.settings.followers)}"></div><div class="field"><label>Following Stat</label><input id="sFing" value="${esc(data.settings.following)}"></div></div></div><button class="btn primary" onclick="saveSettings()">Save Settings</button></div>`}
function saveSettings(){data.settings.siteName=$('sName').value;data.settings.tagline=$('sTag').value;data.settings.whatsapp=$('sWa').value;data.settings.whatsappNumber=$('sWan').value.replace(/\D/g,'');data.settings.followers=$('sFol').value;data.settings.following=$('sFing').value;save();render();}
function renderServices(){$('services').innerHTML=`<div class="card"><div class="actions" style="justify-content:space-between"><h2>Services</h2><button class="btn primary" onclick="openService()">+ Add Service</button></div><div class="item-list">${data.services.map(s=>`<div class="item"><div class="item-main"><div class="item-icon">${esc(s.icon)}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.description)}</p></div></div><div class="actions"><span class="tag ${s.active?'':'off'}">${s.active?'Active':'Hidden'}</span><button class="btn" onclick="toggleService('${s.id}')">${s.active?'Hide':'Show'}</button><button class="btn" onclick="openService('${s.id}')">Edit</button><button class="btn danger" onclick="deleteService('${s.id}')">Delete</button></div></div>`).join('')}</div></div>`}
function openService(id){const s=id?data.services.find(x=>x.id===id):{id:'service-'+Date.now(),title:'',icon:'★',color:'blue',description:'',active:true};const isNew=!id;modal(`<h2>${isNew?'Add':'Edit'} Service</h2><div class="field"><label>Name</label><input id="mTitle" value="${esc(s.title)}"></div><div class="field"><label>Icon</label><input id="mIcon" value="${esc(s.icon)}"></div><div class="field"><label>Color class</label><select id="mColor"><option ${s.color==='blue'?'selected':''}>blue</option><option ${s.color==='purple'?'selected':''}>purple</option><option ${s.color==='pink'?'selected':''}>pink</option><option ${s.color==='orange'?'selected':''}>orange</option></select></div><div class="field"><label>Description</label><textarea id="mDesc">${esc(s.description)}</textarea></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="saveService('${s.id}',${isNew})">Save</button></div>`)}
function saveService(id,isNew){const obj={id,title:$('mTitle').value.trim(),icon:$('mIcon').value.trim(),color:$('mColor').value,description:$('mDesc').value.trim(),active:true};if(!obj.title)return;if(isNew)data.services.push(obj);else Object.assign(data.services.find(x=>x.id===id),obj);closeModal();save();render();}
function toggleService(id){const s=data.services.find(x=>x.id===id);s.active=!s.active;save();render();}
function deleteService(id){if(confirm('Delete this service?')){data.services=data.services.filter(x=>x.id!==id);save();render();}}
function renderPlatforms(){$('platforms').innerHTML=`<div class="card"><div class="actions" style="justify-content:space-between"><h2>Platforms</h2><button class="btn primary" onclick="openPlatform()">+ Add Platform</button></div><div class="item-list">${data.platforms.map(p=>`<div class="item"><div class="item-main"><div class="item-icon">${esc(p.icon)}</div><div><h3>${esc(p.name)}</h3><p>${esc(p.subtitle)} · ${p.services.join(', ')}</p></div></div><div class="actions"><span class="tag ${p.active?'':'off'}">${p.active?'Active':'Hidden'}</span><button class="btn" onclick="togglePlatform('${p.id}')">${p.active?'Hide':'Show'}</button><button class="btn" onclick="openPlatform('${p.id}')">Edit</button><button class="btn danger" onclick="deletePlatform('${p.id}')">Delete</button></div></div>`).join('')}</div></div>`}
function openPlatform(id){const p=id?data.platforms.find(x=>x.id===id):{id:'platform-'+Date.now(),name:'',icon:'●',logoClass:'tiktok-logo',subtitle:'Social Media Boosting',services:['Followers','Views'],active:true};const isNew=!id;modal(`<h2>${isNew?'Add':'Edit'} Platform</h2><div class="grid2"><div><div class="field"><label>Name</label><input id="pName" value="${esc(p.name)}"></div><div class="field"><label>Icon</label><input id="pIcon" value="${esc(p.icon)}"></div><div class="field"><label>Logo CSS class</label><input id="pLogo" value="${esc(p.logoClass)}"></div></div><div><div class="field"><label>Subtitle</label><input id="pSub" value="${esc(p.subtitle)}"></div><div class="field"><label>Services (comma separated)</label><input id="pServices" value="${esc(p.services.join(', '))}"></div></div></div><div class="actions"><button class="btn" onclick="closeModal()">Cancel</button><button class="btn primary" onclick="savePlatform('${p.id}',${isNew})">Save</button></div>`)}
function savePlatform(id,isNew){const obj={id,name:$('pName').value.trim(),icon:$('pIcon').value.trim(),logoClass:$('pLogo').value.trim(),subtitle:$('pSub').value.trim(),services:$('pServices').value.split(',').map(x=>x.trim()).filter(Boolean),active:true};if(!obj.name)return;if(isNew)data.platforms.push(obj);else Object.assign(data.platforms.find(x=>x.id===id),obj);closeModal();save();render();}
function togglePlatform(id){const p=data.platforms.find(x=>x.id===id);p.active=!p.active;save();render();}
function deletePlatform(id){if(confirm('Delete this platform?')){data.platforms=data.platforms.filter(x=>x.id!==id);save();render();}}
function modal(content){const d=document.createElement('div');d.id='modal';d.className='modal';d.innerHTML=`<div class="modal-card">${content}</div>`;document.body.appendChild(d)}function closeModal(){$('modal')?.remove()}
function go(page){document.querySelectorAll('.side').forEach(x=>x.classList.toggle('active',x.dataset.page===page));document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===page));$('pageTitle').textContent=page.charAt(0).toUpperCase()+page.slice(1)}
document.querySelectorAll('.side').forEach(b=>b.addEventListener('click',()=>go(b.dataset.page)));
$('saveAll').addEventListener('click',()=>save());
$('loginForm').addEventListener('submit',e=>{e.preventDefault();if($('adminUser').value==='admin'&&$('adminPass').value==='ctk12345'){sessionStorage.setItem('ctk_admin','1');$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');render()}else $('loginMsg').textContent='Invalid demo login.'});
$('logout').addEventListener('click',()=>{sessionStorage.removeItem('ctk_admin');location.reload()});
if(sessionStorage.getItem('ctk_admin')){$('loginView').classList.add('hidden');$('appView').classList.remove('hidden');render()}
